name: Reminder Notifications
true:
  schedule:
  - cron: '*/5 * * * *'
  workflow_dispatch: null
jobs:
  reminder-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install pytz pyTelegramBotAPI pyyaml

        '
    - env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      name: Run the reminder script
      run: python reminder_bot.py
'on':
  schedule:
  - cron: '*/5 * * * *'
  - cron: 0 11 * * *
  - cron: 0 9 * * *
  - cron: 0 14 * * *
  - cron: 0 10 * * SAT
  - cron: 0 11 * * SUN
  - cron: 0 16 * * SAT
